name: Deploy Website to Github Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies (if any)
        run: |
          if [ -f package.json ]; then
            npm install
          fi
      
      - name: Run linting
        run: npm run lint || true

      - name: Build Project
        run: |
          if [ -f package.json ]; then
            npm run build-pages
          fi

      # - name: Upload logs
      #   run: |
      #     mkdir logs
      #     echo "Logs uploaded on $(date)" > logs/summary.log
      #     tar -czf logs.tar.gz logs
      #   continue-on-error: true

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build